### ISSUE TITLE
kernelspec handled differently between nteract and Jupyter

### ISSUE THREAD

**Issue by rwb27** [nteract/spawnteract#42]
**Application or Package Used**
nteract desktop

**Describe the bug**
I have a kernelspec on my system that starts a kernel in Windows Subsystem Linux.  This requires me to:
1. prepend ``wsl.exe`` to the ``argv`` entry in ``kernel.json``
2. replace ``{connection_file}`` with `` `wslpath -a '{connection_file}'` ``
Doing this works in Jupyter notebooks running on Windows, but nteract just fails to connect

**To Reproduce**

Create an ipython kernel on WSL, copy over the kernelspec file to your Windows kernelspec folder, and try to select the kernel in nteract.  Error messages are visible in the debug console.

**Expected behavior**
I was hoping it would connect to the kernel like Jupyter does.

**Desktop (please complete the following information):**

- OS: Windows 10
- Browser using desktop app
- Version 0.15

**Additional context**
Perhaps phrasing this as a bug is putting it incorrectly; the kernelspec file is being handled differently than it gets handled by Jupyter.  I suspect one issue is that the {connection_file} placeholder is only being substituted when it's an entire argument, rather than when it's a substring.  There may also be an issue about how (or whether) backslashes are being escaped in the arguments.

I have worked around it with a Python wrapper script here, though I'm not convinced it isn't slowing the kernel down: https://gitlab.com/snippets/1898108

I realise this is a slightly silly edge case, but I thought I'd mention it.  I don't know your codebase well enough even to start looking for where I could fix it, but I'd happily send a PR if it is something I could attempt.  A hint at where the source code is that deals with starting the kernels would be lovely though.

Alternatively, if there is an established solution for using WSL kernels, I'd be very grateful if you could point me at it - I've not found one yet.

**Comment by rwb27** [comment]
Sure, thanks for making time to look at a crazy fringe case like this!  I have reconstructed my previous kernelspec, and the error is:
```
Logging kernel py3-scipy-broken (ref 3497679c-802c-46bb-bdd1-684f8b72a12b) stdout and stderr to javascript console in this color    <<<<
app.js:2751 Traceback (most recent call last):
  File "/usr/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/mnt/c/Users/rwb34/dev/venvs/py3-scipy/lib/python3.7/site-packages/ipykernel_launcher.py", line 16, in <module>
    app.launch_new_instance()
  File "/mnt/c/Users/rwb34/dev/venvs/py3-scipy/lib/python3.7/site-packages/traitlets/config/application.py", line 657, in launch_instance
    app.initialize(argv)
  File "</mnt/c/Users/rwb34/dev/venvs/py3-scipy/lib/python3.7/site-packages/decorator.py:decorator-gen-124>", line 2, in initialize
  File "/mnt/c/Users/rwb34/dev/venvs/py3-scipy/lib/python3.7/site-packages/traitlets/config/application.py", line 87, in catch_config_error
    return method(app, *args, **kwargs)
  File "/mnt/c/Users/rwb34/dev/venvs/py3-scipy/lib/python3.7/site-packages/ipykernel/kernelapp.py", line 472, in initialize
    self.write_connection_file()
  File "/mnt/c/Users/rwb34/dev/venvs/py3-scipy/lib/python3.7/site-packages/ipykernel/kernelapp.py", line 199, in write_connection_file
    iopub_port=self.iopub_port, control_port=self.control_port)
  File "/mnt/c/Users/rwb34/dev/venvs/py3-scipy/lib/python3.7/site-packages/jupyter_client/connect.py", line 137, in write_connection_file
    with open(fname, 'w') as f:
PermissionError: [Errno 13] Permission denied: '/mnt/c/Program Files/nteract/{connection_file}'
```

You can see that the ``{connection_file}`` isn't getting substituted, and that's exactly what I'd expect from the line you linked to.  I'm not currently set up to compile nteract from source, but if I get time over the holidays I might take a look.  It might be as simple as replacing that line with a string substitution, which would be nice!

**Comment by captainsafia** [comment]
@rwb27 Sounds good! I suspect the only thing you need to build from source is spawnteract which is a lot easier to get a dev setup for than the nteract desktop app.

Feel free to ping on slack.nteract.io for help on this. I'm @captainsafia on there as well.

**Comment by rwb27** [comment]
Thanks @captainsafia, I've finally found a moment to test this out.  The first thing I learned is that the tests in ``spawn_spec.js`` don't actually check that the kernel is working (i.e. if I change the code to use my WSL kernel, the tests all still pass).  I think a more stringent test (connecting to the kernel and checking it's actually alive) would bloat the test suite with unnecessary imports, so instead I knocked up a very basic script that would start a kernel and wait for a keypress before killing it:

```javascript
const expect = require("chai").expect;
const fs = require("fs");

const launch = require("../").launch;
const kernelspecs = require("kernelspecs");

const readline = require('readline');

function cleanup(connectionFile) {
  // cleanup after our test, fail silently if the test failed
  try {
    fs.unlinkSync(connectionFile);
  } catch (e) {
    return;
  }
}

let spawnResult;
let kernelName;

const rl = readline.createInterface({
    input: process.stdin,
    output: process.stdout
});

kernelspecs.findAll()
.then(kernels => {
    const kernel = kernels['wsl-py3-scipy'];
    kernelName = kernel.name;
    return launch(kernelName);
})
.then(c => {
    spawnResult = c;
    console.log(c.connectionFile);

    rl.question('Hit enter to close the connection ', (answer) => {
        console.log(`attempting to kill the ipython kernel process...`);
        spawnResult.spawn.kill();
        console.log(`closed`);
        rl.close();
      });
});
```
This allows me to connect using an ipython qtconsole (or anything else that accepts a connection file) to test if the kernel is working.

Actually, the readline thing didn't work - it just hangs.  However, the kernel does get spawned, so the only problem is that I had to kill the process rather than closing it politely, which means the connection file doesn't get deleted.

**Comment by rwb27** [comment]
I've tested two versions: the current master branch (works with normal kernels, doesn't work with a simply-wrapped Windows Subsystem Linux kernel), and the one modified line that does string substitution (works for everything).  I've sent a PR as #43 .

Thanks for all your help!

**Comment by captainsafia** [comment]
Cool! Thanks for taking the time to digging into this!
